// Generated by simple Fangless Python transpiler
#include "../c++/runtime.hpp"

// Compile with something like:
//   g++ -std=c++17 output.cpp -o program

PyValue hola(PyValue a, PyValue b) {
    return py_add(a, b);
    return PyValue();
}

PyValue fib(PyValue n) {
    if (py_or(py_eq(n, PyValue(1)), py_eq(n, PyValue(2))).is_truthy()) {
        return PyValue(1);
    }
    else {
        return py_add(fib(py_sub(n, PyValue(1))), fib(py_sub(n, PyValue(2))));
    }
    return PyValue();
}

int main() {
    PyValue a;
    PyValue b;
    py_print(hola(PyValue(1), PyValue(2)));
    a = PyValue(4);
    py_print(a);
    b = PyValue(5);
    a = PyValue("hola");
    b = py_add(a, py_str(b));
    py_print(b);
    py_print(fib(PyValue(5)));
    return 0;
}