// Generated by simple Fangless Python transpiler
#include "../c++/runtime.hpp"

// Compile with something like:
//   g++ -std=c++17 output.cpp -o program

PyValue hola(PyValue a, PyValue b) {
    return py_add(a, b);
    return PyValue();
}

PyValue fib(PyValue n) {
    if (py_or(py_eq(n, PyValue(1)), py_eq(n, PyValue(2))).is_truthy()) {
        return PyValue(1);
    }
    else {
        return py_add(fib(py_sub(n, PyValue(1))), fib(py_sub(n, PyValue(2))));
    }
    return PyValue();
}

int main() {
    PyValue a;
    PyValue b;
    PyValue c;
    PyValue e;
    PyValue i;
    py_print(hola(PyValue(1), PyValue(2)));
    py_print(fib(PyValue(5)));
    a = PyValue(4);
    py_print(a);
    b = PyValue(5);
    a = PyValue("hola");
    b = py_add(a, py_str(b));
    py_print(b);
    a = py_list(std::vector<PyValue>{ PyValue(1), PyValue("hola"), py_dict(std::vector<std::pair<PyValue, PyValue>>{ std::make_pair(PyValue("z"), PyValue(1)), std::make_pair(PyValue("x"), PyValue("ECCI")) }), py_list(std::vector<PyValue>{ PyValue(1), PyValue(2), PyValue(3), PyValue(4) }), py_tuple(std::vector<PyValue>{ PyValue(1), PyValue(2), PyValue(3), PyValue(4) }) });
    py_print(a);
    py_print(PyValue("Fibonacci"));
    {
        PyValue __range_start = PyValue(0);
        PyValue __range_stop = py_sub(py_len(a), PyValue(1));
        PyValue __range_step = PyValue(1);
        for (long long __i = __range_start.int_value; __i < __range_stop.int_value; __i += __range_step.int_value) {
            i = PyValue(__i);
            py_print(py_getitem(a, i));
        }
    }
    {
        PyValue __iter = py_getitem(a, PyValue(3));
        if (__iter.type != PyValue::LIST && __iter.type != PyValue::TUPLE) { throw std::runtime_error("TypeError: can only iterate over list or tuple in for-loop"); }
        if (__iter.type == PyValue::LIST) {
            for (std::size_t __idx = 0; __idx < __iter.list_value.size(); ++__idx) {
                e = __iter.list_value[__idx];
                py_print(e);
            }
        } else {
            for (std::size_t __idx = 0; __idx < __iter.tuple_value.size(); ++__idx) {
                e = __iter.tuple_value[__idx];
                py_print(e);
            }
        }
    }
    a = PyValue(5);
    b = PyValue(10);
    while (py_lt(a, b).is_truthy()) {
        py_print(fib(py_sub(b, PyValue(5))));
        c = b;
        b = PyValue("hola");
        b = py_sub(c, PyValue(2));
    }
    py_print(PyValue("Si printeo mis probabilidades de graduarme suben :)"));
    return 0;
}